[default]
src = 'src'
out = 'out'
libs = ['lib']
solc-version = "0.8.15"
optimizer = true
via_ir = true
optimizer_runs = 1000000
bytecode_hash = "none"

# See more config options https://github.com/foundry-rs/foundry/tree/master/config